version: '3.7'

services:
  php:
    build:
        context: ./
        dockerfile: php-docker-file
    ports:
        - "8000:80"
    volumes:
        - "./dist:/var/www/html/"
        - "./data:/var/data/dojo:rw"